-- Drop tables if they exist (optional, for clean setup)
-- DROP TABLE registros_chuva CASCADE CONSTRAINTS;
-- DROP TABLE usuarios CASCADE CONSTRAINTS;

-- 1. usuarios table
CREATE TABLE usuarios_otoniel (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) UNIQUE,
  cidade VARCHAR2(100)
);

-- 2. registros_chuva table
CREATE TABLE registros_chuva (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_ocorrencia DATE NOT NULL,
  local VARCHAR2(100) NOT NULL,
  volume_mm NUMBER(5,2) NOT NULL,
  observacoes CLOB,
  usuario_id NUMBER,
  CONSTRAINT fk_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES usuarios(id)
    ON DELETE SET NULL
);

-- Sample data (optional, can be added here or via API calls)
INSERT INTO usuarios (nome, email, cidade) VALUES ('Admin User', 'admin@example.com', 'São Paulo');
INSERT INTO usuarios (nome, email, cidade) VALUES ('João da Silva', 'joao@email.com', 'Campinas, SP');

INSERT INTO registros_chuva (data_ocorrencia, local, volume_mm, observacoes, usuario_id)
VALUES (TO_DATE('2025-06-03', 'YYYY-MM-DD'), 'São Paulo, SP', 25.4, 'Chuva leve durante a tarde', (SELECT id FROM usuarios WHERE email = 'Admin User'));